server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway
  codec:
    max-in-memory-size: 100MB
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true   
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - ${GATEWAY_ALLOWED_ORIGIN:http://localhost:4200}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

        - id: auth-service-oauth
          uri: lb://auth-service
          predicates:
            - Path=/oauth2/**,/login/oauth2/**

        - id: auth-service-docs
          uri: lb://auth-service
          predicates:
            - Path=/v3/api-docs/auth-service
          filters:
            - SetPath=/v3/api-docs

        - id: connectsphere-service
          uri: lb://connectsphere-service
          predicates:
            - Path=/api/v1/posts/**,/api/v1/comments/**,/api/v1/reactions/**,/api/v1/follows/**,/api/v1/reports/**

        - id: media-service
          uri: lb://media-service
          predicates:
            - Path=/api/v1/media/**

        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/api/v1/search/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**

        - id: connectsphere-service-docs
          uri: lb://connectsphere-service
          predicates:
            - Path=/v3/api-docs/connectsphere-service
          filters:
            - SetPath=/v3/api-docs

        - id: media-service-docs
          uri: lb://media-service
          predicates:
            - Path=/v3/api-docs/media-service
          filters:
            - SetPath=/v3/api-docs

        - id: search-service-docs
          uri: lb://search-service
          predicates:
            - Path=/v3/api-docs/search-service
          filters:
            - SetPath=/v3/api-docs

        - id: notification-service-docs
          uri: lb://notification-service
          predicates:
            - Path=/v3/api-docs/notification-service
          filters:
            - SetPath=/v3/api-docs
