server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: search-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3310/connectsphere_search?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:search_user}
    password: ${SPRING_DATASOURCE_PASSWORD:search_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    instance-id: ${spring.application.name}:${server.port}
    non-secure-port: ${SERVER_PORT:8084}
    prefer-ip-address: false
    home-page-url: http://${eureka.instance.hostname}:${server.port}/
    status-page-url: http://${eureka.instance.hostname}:${server.port}/actuator/info
    health-check-url: http://${eureka.instance.hostname}:${server.port}/actuator/health
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
