server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
        - id: auth-service-docs
          uri: lb://auth-service
          predicates:
            - Path=/v3/api-docs/auth-service
          filters:
            - SetPath=/v3/api-docs
        - id: connectsphere-service
          uri: lb://connectsphere-service
          predicates:
            - Path=/api/v1/posts/**
        - id: connectsphere-service-docs
          uri: lb://connectsphere-service
          predicates:
            - Path=/v3/api-docs/connectsphere-service
          filters:
            - SetPath=/v3/api-docs

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    instance-id: ${spring.application.name}:${server.port}
    non-secure-port: ${SERVER_PORT:8080}
    prefer-ip-address: false
    home-page-url: http://${eureka.instance.hostname}:${server.port}/
    status-page-url: http://${eureka.instance.hostname}:${server.port}/actuator/info
    health-check-url: http://${eureka.instance.hostname}:${server.port}/actuator/health
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: auth-service
        url: /v3/api-docs/auth-service
      - name: connectsphere-service
        url: /v3/api-docs/connectsphere-service
